name: Ansible Vault Test

on:
    push:
        branches: [ main ]

jobs:
    Test-Vault:
        name: Test Vault + Ansible
        runs-on: ubuntu-latest

        steps:
            - name: checkout
              uses: actions/checkout@v4

            - name: Setup Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.11"

            - name: Install Ansible
              run: |
                  pip install ansible hvac
                  ansible-galaxy collection install community.hashi_vault
            - name: Run Playbook
              env:
                  VAULT_TOKEN: ${{secrets.VAULT_TOKEN}}
                  VAULT_ADDR: ${{secrets.VAULT_ADDR}}
              run: |
                  ansible-playbook playbooks/setup.yml
